### ISSUE TITLE
[question]When using this plugin, do users need to solve the internal network penetration problem themselves?

### ISSUE THREAD

**Issue by ayamzh** [karrarrahim/NetickForUnity#11]
When using this plugin, do users need to solve the internal network penetration problem themselves?

**Comment by karrarrahim** [comment]
I am not sure what you mean, but if you mean NAT punchthrough, then that's up to the transport or service you are using. Netick only deals with the actual gameplay synchronization.

**Comment by karrarrahim** [comment]
Going to close the case. Please use [Discord ](https://discord.com/invite/uV6bfG66Fx )for support questions.
