### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ArvinCheng2019** [karrarrahim/NetickForUnity#3]
Hello,

We are currently developing a game where 10 players battle in a room. We would like to test the provided demo over the internet, but we're unsure how to deploy the project to a server. Is there any documentation available?

Thank you.

**Comment by karrarrahim** [comment]
Hi,

It works the same way as any other networking solution. You upload a build of your game and run it as headless in a dedicated server using any cloud service: AWS, Google Cloud, etc. Then you can connect to it using its IP and Port.

Please use the discord for help questions: https://discord.com/invite/uV6bfG66Fx
