### ISSUE TITLE
[Feature Request] NetworkObjectRef QOL

### ISSUE THREAD

**Issue by StinkySteak** [karrarrahim/NetickForUnity#5]
1. Add `IsValid` check
2. Add `ToString()`

**Comment by StinkySteak** [comment]
Add == operator

**Comment by karrarrahim** [comment]
Done.

**Comment by StinkySteak** [comment]
There is `Equals` but no == operator

**Comment by karrarrahim** [comment]
I just added it, it will be coming in the next commit.
