### ISSUE TITLE
Does Network Properties support the byte[] type?

### ISSUE THREAD

**Issue by ayamzh** [karrarrahim/NetickForUnity#6]
I need to synchronize a data type of byte[]. Is this type supported? We are developing an Oculus game that utilizes the avatar system provided by Oculus, where the avatar data is in this format: public byte[] RecordStreamData(StreamLOD lod).

**Comment by karrarrahim** [comment]
Yes: https://netick.net/docs/2/articles/networked-state.html#network-arrays

Please use our Discord server for support questions: https://discord.com/invite/uV6bfG66Fx
