### ISSUE TITLE
[Question] How to create rooms?

### ISSUE THREAD

**Issue by krytoou** [karrarrahim/NetickForUnity#9]
Hello, just want to know if it's possible to create rooms in your framework?
Something similar to Photon PUN.
So we have a server to which players can connect and there create sub-servers (rooms).
Is that possible here?

**Comment by StinkySteak** [comment]
No, What you are talking about is more of cloud tech. It is possible using any of these:
- Unity Lobby
- Photon Realtime Transport for Netick

**Comment by krytoou** [comment]
I see. Just want to find framework that will have it included.
Like Photon PUN2 (rooms) but also can handle server predictions (for example for soccer ball object and make it interact with all players , like in Fusion but without Input delays).

**Comment by StinkySteak** [comment]
Treat Netick as Fusion but no Rooms/sessions/lobby built-in
